bookRentWebApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('core.urls')), # path is blank as we want the front page to open
    path('items/', include('item.urls')), # all urls that contain items/ will automatically goto item urls.py
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
#the above code helps to display images while developing a website (not to be used in production)

conversation/urls.py
from django.urls import path
from . import views
app_name = 'conversation'

urlpatterns = [
    path('',views.inbox, name = 'inbox'),
    path('<int:pk>/',views.detail, name = 'detail'),
    path('new/<int:item_pk>/', views.new_conversation,name = 'new'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('contact/',views.contact, name = 'contact'),
    path('signup/',views.signup, name = 'signup'),
    path('login/',auth_views.LoginView.as_view(template_name ='core/login.html',authentication_form = LoginForm), name = 'login')
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name = 'index'),
]

item/urls.py
#This code defines URL patterns for a Django application named "item". Specifically, it maps a URL to a view function, which will handle the logic when a user visits that URL.
#app_name is set to 'item', which is used for namespacing URLs in this Django application. This is helpful when you have multiple apps in your project and want to ensure URL names are unique across the project.
#name='detail' assigns a name to this URL pattern, which can be used to refer to this URL in templates and other parts of your Django project.
from django.urls import path
from . import views

app_name = 'item'

#pk (integer) has to be same as set in views.py of item folder
#next Step: import this file in main urls.py
urlpatterns = [
    path('',views.items,name = 'items'),
    path('new/', views.new, name = 'new'),
    path('<int:pk>/',views.detail, name = 'detail'),
    path('<int:pk>/delete/',views.delete, name = 'delete'),
    path('<int:pk>/edit/',views.edit, name = 'edit'),

    
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget = forms.TextInput(attrs={
        'placeholder': 'Enter username',
        'class': 'w-full px-6 py-4 rounded-xl'
    }))
    password = forms.CharField(widget = forms.PasswordInput(attrs={
            'placeholder': 'Enter Password',
            'class' : 'w-full py-4 px-6 rounded-xl' 
        }) )

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget = forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class' : 'w-full py-4 px-6 rounded-xl' 
    }) )
    email = forms.CharField(widget = forms.EmailInput(attrs={
        'placeholder': 'Your email Id',
        'class' : 'w-full py-4 px-6 rounded-xl' 
    }) )
    password1 = forms.CharField(widget = forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class' : 'w-full py-4 px-6 rounded-xl' 
    }) )
    password2 = forms.CharField(widget = forms.PasswordInput(attrs={
        'placeholder': 'Re-Enter Password',
        'class' : 'w-full py-4 px-6 rounded-xl' 
    }) )
    

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignUpForm
# Create your views here.

#Combines a given template with a given context dictionary and returns an HttpResponse object with that rendered text
def index(request):
    #only shows available items and 6 on page
    items = Item.objects.filter(is_sold = False)[0:6]

    #display all categories
    categories = Category.objects.all()
    return render(request, 'core/index.html',{
        'categories': categories,
        'items': items,
    }) 

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form,
    })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset = "utf-8">
        <meta name = "viewport" content ="width=device-width, inital-scale = 1.0">

        <script src= "https://cdn.tailwindcss.com"></script>

        <title> {% block title %}{% endblock%} |  BookRing </title>
    </head>

    <body> 

        <nav class ="py-6 px-6 flex justify-between items-center border-b border-blue-200">
            <a href ="/" class ="text-xl font-semibold">ReadingRing</a>
            {% comment %} 
            / link directs you to home page
            # link will not do anything, it is inactive
            # w-2/3 means 2/3rd of the footer is taken, pr - padding towards right
            {% endcomment %}
            <div class ="space-x-6">
                <a href = "{% url 'item:items' %}" class ="text-lg font-semibold hover:text-gray-500">Browse</a>
                <a href = "{% url 'item:new' %}" class = "text-lg font-semibold hover:text-gray-500">New Item</a>

                {% if request.user.is_authenticated %}
                    <a href = "{% url 'conversation:inbox' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href = "{% url 'dashboard:index' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Dashboard</a>

                {% else %}
                    <a href = "{% url 'core:signup' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                    <a href = "{% url 'core:login' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Login</a> 
                {% endif %}
            </div>
                
        </nav>

        <div class ="px-6 py-6">
            {% block content %}
            
            {% endblock %} 
        </div>

        <footer class ="px-6 py-6 flex justify-between bg-gray-800">
            <div class ="w-2/3 pr-10">
                <h3 class ="mb-5 font-semibold text-gray-400"> About</h3>
                <p class ="text-lg text-gray-500"> This is an online book renting site where people can put their books on rent and as well as get books on rent too. We manage everything from security of your precious books to end-to-end delivery </p>
            </div>

            <div class = "w-1/3">
                <h3 class ="font-semibold text-gray-400">Menu</h3>

                <ul class ="space-y-2">
                    <li><a href="#" class = "text-lg text-teal-500 hover:text-teal-700">About</a></l1>
                    <li><a href="{% url 'core:contact' %}" class = "text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class = "text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
                    <li><a href="#" class = "text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% block title %} Contact {% endblock %}


{% block content %}
    <h1> The Contact Page </h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %} Welcome {% endblock %}


{% block content %}

{% comment %} mt-6 is margin top 6 {% endcomment %}
    <div class = "mt-6 px-6 py-3 bg-gray-100 rounded-xl">
        <h2 class = "mb-12 text-2xl text-center"> Newest Items</h2>

        <div class ="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src = "{{ item.image.url }}" class ="rounded-xl object-contain h-80 w-40">
                        </div>
                        
                            <h2 class = "text-2xl"> {{ item.name }} </h2>
                            <p class = "text-gray-500"> {{item.price}} </p>
                        
                    </a>
                </div>
            {% endfor %}
        </div>
    <div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class = "mb-12 text-2xl text-center" >Categories</h2>
        
        <div class= "grid grid-cols-3 gap-3">
            {% for category in categories %}
                <a href = "#">
                    <div class ="p-6 bg-white">
                        <h2 class = "text-2xl"> {{ category.name }}</h3>
                        <p class = "text-gray-500"> {{ category.items.count}} items </p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Log in {% endblock %}

{% block content %}

<div class = "w-1/2 my-6 p-6 mx-auto  bg-gray-100 rounded-xl font-semibold">
    <h1 class = "mb-6 text-2xl"> Log in </h2>
    <form method = 'POST' action = '.'>
        {% csrf_token %}
        <div class = "mb-3">
            <label class = "inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class = "mb-3">
            <label class = "inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class = "mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class = "text-lg px-8 py-4 bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Submit </button>
    </form>
</div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign Up{% endblock %}

{% block content%} 

<div class = "w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl font-semibold "> 
    <h1 class = "mb-6 text-2xl"> Sign up </h1>

    <form method = 'post' action = '.'>
        {% csrf_token %}
        <div class = "mb-3">
            <label class = "inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class = "mb-3">
            <label class = "inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>
        <div class = "mb-3">
            <label class = "inline-block mb-2">Passsword</label><br>
            {{ form.password1 }}
        </div>
        <div class = "mb-3">
            <label class = "inline-block mb-2">Repeat Password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class = "mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class ="px-8 py-4 text-lg text-white bg-teal-500 hover:bg-teal-700 rounded-xl">Submit</button>
    </form>
</div>

{% endblock %}