bookRentWebApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('core.urls')), # path is blank as we want the front page to open
    path('items/', include('item.urls')), # all urls that contain items/ will automatically goto item urls.py
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
#the above code helps to display images while developing a website (not to be used in production)

conversation/urls.py
from django.urls import path
from . import views
app_name = 'conversation'

urlpatterns = [
    path('',views.inbox, name = 'inbox'),
    path('<int:pk>/',views.detail, name = 'detail'),
    path('new/<int:item_pk>/', views.new_conversation,name = 'new'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('contact/',views.contact, name = 'contact'),
    path('signup/',views.signup, name = 'signup'),
    path('login/',auth_views.LoginView.as_view(template_name ='core/login.html',authentication_form = LoginForm), name = 'login')
]

item/urls.py
#This code defines URL patterns for a Django application named "item". Specifically, it maps a URL to a view function, which will handle the logic when a user visits that URL.
#app_name is set to 'item', which is used for namespacing URLs in this Django application. This is helpful when you have multiple apps in your project and want to ensure URL names are unique across the project.
#name='detail' assigns a name to this URL pattern, which can be used to refer to this URL in templates and other parts of your Django project.
from django.urls import path
from . import views

app_name = 'item'

#pk (integer) has to be same as set in views.py of item folder
#next Step: import this file in main urls.py
urlpatterns = [
    path('',views.items,name = 'items'),
    path('new/', views.new, name = 'new'),
    path('<int:pk>/',views.detail, name = 'detail'),
    path('<int:pk>/delete/',views.delete, name = 'delete'),
    path('<int:pk>/edit/',views.edit, name = 'edit'),

    
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# Creating a new database model

class Category(models.Model):
    name = models.CharField(max_length =255)

    class Meta:
        # alphateical ordering
        ordering = ('name',)

        #changes the default django categorys to categories
        verbose_name_plural = 'Categories'
    
    # returns the actual vallues of the objects in a Category and not like Category object (1)
    def __str__(self):
        return self.name

class Item(models.Model):
    #links the item to its category, if the category is deleted all items in the category also get deleted
    category = models.ForeignKey(Category, related_name ='items', on_delete =models.CASCADE)
    
    name = models.CharField(max_length =255)
    description = models.TextField(blank =True, null= True)
    price = models.FloatField()
    image = models.ImageField(upload_to ='item_images',blank =True, null =True)
    is_sold = models.BooleanField(default = False)
    created_by = models.ForeignKey(User, related_name ='items', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return self.name
    

    

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border' 

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item

        #if you put {} instead of () the order will be random.
        #if you donot put , after  the last item nothing will be printed as (image,) -> this is interpred as tuple (image) is interpreted as just a string in python
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item

        #if you put {} instead of () the order will be random.
        #if you donot put , after  the last item nothing will be printed as (image,) -> this is interpred as tuple (image) is interpreted as just a string in python
        fields = ('category', 'name', 'description', 'price', 'image','is_sold')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q #this helps when we are searching for an item and want to find all the items which have a particular word in their name or description
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm, EditItemForm
from .models import Item, Category
# Create your views here.

def items(request):
    query = request.GET.get('query','')
    items = Item.objects.filter(is_sold = False)
    categories = Category.objects.all()
    category_id = request.GET.get('category',0)

    if category_id:
        items = items.filter(category_id = category_id)
    if query:
        items = items.filter(Q(name__icontains = query) | Q(description__icontains = query))

    return render(request, 'item/items.html',{
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):

    #if item not present in DB it return 404 error, pk is the primary key given in request
    #the loading html page is present in templates 
    item = get_object_or_404(Item, pk = pk)

    #to show the related items below the selected item description
    related_items = Item.objects.filter(category = item.category, is_sold = False).exclude(pk = pk)[0:3]

    return render(request, 'item/detail.html',{
        'item': item,
        'related_items': related_items,
    })

#if not logged in the user will be directed to the login page
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES) #it will save the data

        if form.is_valid():
            item  = form.save(commit = False) #as commit is false it will only create an object but not save it to the DB
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk = item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html',{
        'form' : form,
        'title' : 'New item',
    })

@login_required
def edit(request, pk):

    item = get_object_or_404(Item, pk=pk, created_by = request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES,instance = item) #it will save the data

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk = item.id)
    else:
        form = EditItemForm(instance = item)

    return render(request, 'item/form.html',{
        'form' : form,
        'title' : 'Edit item',
    })

@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{item.name}} {% endblock %}

{% block content %}
<div class = "grid grid-cols-5 gap-6">
    <div class ="col-span-2">
        <img src = "{{ item.image.url}}" class = "rounded-xl">
    </div>

    <div class ="col-span-3 bg-gray-100 p-6 rounded-xl">
        <h1 class = "mb-6 text-3xl">{{item.name}} </h1>
        <p class = "text-gray-500"><strong>Price: </strong>{{item.price}}</p>
        <p class = "text-gray-500"><strong>Seller: </strong> {{item.created_by}}</p>
        {%if item.description%}
        <p class = "text-gray-700"><strong class = "text-gray-500">Description:</strong><br> {{item.description}}</p>
        {%endif%}

        {% if request.user == item.created_by %}
            <div class = "mt-6 p-6 bg-white rounded-xl">
                <p> This is your item! </p>
                <a href = "{% url 'item:edit' item.id %}" class = "inline-block text-lg text-white mt-6 px-6 py-3 font-semibold bg-teal-500 rounded-xl">Edit Item</a>
                <a href ="{% url 'item:delete' item.id %}" class = "inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Remove Item</a>
            </div>
        {% else %}
            <a href = "{% url 'conversation:new' item.id %}" class= "mt-6 px-6 py-3 text-lg font-semibold inline-block bg-teal-500 hover: bg-teal-700 text-white rounded-xl"> Contact Seller</a>
        {% endif %}
    </div>
</div>


<h2 class = "mt-6 text-xl"> Similar Items </h2>
<div class ="grid grid-cols-3 gap-3">
    {% for item in related_items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src = "{{ item.image.url }}" class ="rounded-xl object-contain h-80 w-40">
                </div>
                
                    <h2 class = "text-2xl"> {{ item.name }} </h2>
                    <p class = "text-gray-500"> {{item.price}} </p>
                
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<h1 class = "mb-6 text-3xl"> {{ title }}</h1>
{% comment %} enctype is required to upload image files {% endcomment %}
<form method = 'post' action ='.' enctype = 'multipart/form-data'>  
    {% csrf_token %}

    <div class = "space-y-4">
        {{form.as_p}}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class = " mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}

            {{ form.non_field_errors}}
        </div>
    {% endif %}
    <button class = "mt-6 text-lg px-8 py-4 mb-6 rounded-xl bg-teal-500 hover:bg-teal-700 text-semibold text-white">Submit</button>
</form>

{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items {% endblock %}

{% block content %}
    <div class = "pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class = "col-span-1">
            <form method = 'get' action = "{% url 'item:items' %}"> 
                <input name = "query" class = "w-full py-4 border rounded-xl" type = "text" value = "{{ query }}" placeholder = "What would you like to read? ">
                <button class = "mt-2 py-4 px-8 text-lg rounded-xl bg-teal-500 text-white hover:bg-teal-700">Search</button>
            </form>

            <hr class = "my-6">

            <p class ="font-semibold"> Categories </p>

            <ul>
                {% for category in categories %}
                    <li class = "py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href = "{% url 'item:items' %}?query= {{ query }}&category= {{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <p class = 'font-semibold'> Clear filters</p>
            <ul>
                <li class = "inline-block px-2 py-2 rounded-xl bg-yellow-200 "><a href = "{% url 'item:items' %}">Clear</a></li>
            </ul>

        </div>
        <div class = "col-span-3">
            <div class ="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src = "{{ item.image.url }}" class ="rounded-xl object-contain h-80 w-40">
                            </div>
                            
                                <h2 class = "text-2xl"> {{ item.name }} </h2>
                                <p class = "text-gray-500"> {{item.price}} </p>
                            
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}